services:
  docky:
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    hostname: docker
    entrypoint: ["poetry", "run"]
    command: ["/bin/bash"]
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        GROUP_ID: ${GROUP_ID}
        USER_ID: ${USER_ID}
        USER_NAME: ${USER_NAME}
        WORK_DIR: ${WORK_DIR}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
      - type: volume
        source: virtual-environment
        target: ${WORK_DIR}/.venv/

volumes:
  virtual-environment:
